/////////// AUTH_LOGIN

export const AUTH_LOGIN_REQUEST = 'AUTH_LOGIN_REQUEST';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_FAILURE = 'AUTH_LOGIN_FAILURE';

/////////// AUTH_LOGOUT

export const AUTH_LOGOUT_REQUEST = 'AUTH_LOGOUT_REQUEST';
export const AUTH_LOGOUT_SUCCESS = 'AUTH_LOGOUT_SUCCESS';
export const AUTH_LOGOUT_FAILURE = 'AUTH_LOGOUT_FAILURE';

/////////// ADVERTS

export const ADVERTS_LOADED_REQUEST = 'ADVERTS_LOADED_REQUEST';
export const ADVERTS_LOADED_SUCCESS = 'ADVERTS_LOADED_SUCCESS';
export const ADVERTS_LOADED_FAILURE = 'ADVERTS_LOADED_FAILURE';

/////////// ADVERT

export const ADVERT_LOADED_REQUEST = 'ADVERT_LOADED_REQUEST';
export const ADVERT_LOADED_SUCCESS = 'ADVERT_LOADED_SUCCESS';
export const ADVERT_LOADED_FAILURE = 'ADVERT_LOADED_FAILURE';

/////////// CREATE ADVERT

export const ADVERT_CREATED_REQUEST = 'ADVERT_CREATED_REQUEST';
export const ADVERT_CREATED_SUCCESS = 'ADVERT_CREATED_SUCCESS';
export const ADVERT_CREATED_FAILURE = 'ADVERT_CREATED_FAILURE';

/////////// UI

export const UI_RESET_ERROR = 'UI_RESET_ERROR';
