export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_FAILURE = 'AUTH_LOGIN_FAILURE';
export const AUTH_LOGIN_REQUEST = 'AUTH_LOGIN_REQUEST';

export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const ADVERTS_LOADED = 'ADVERTS_LOADED';
export const ADVERTS_CREATED = 'ADVERTS_CREATED';
